config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'word_game#game'
  get 'score', to: 'word_game#score'

  root to: 'word_game#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/word_game_controller.rb
require 'open-uri'
require 'json'
# require 'date'
# require 'time'

class WordGameController < ApplicationController

  def home
  end

  def game
    @grid = generate_grid(9)
    @start_time = Time.now
  end

  def score
    @attempt = params[:attempt]
    @grid = params[:grid]
    @start_time = params[:start_time].to_time
    @end_time = Time.now
    @result = run_game(@attempt, @grid, @start_time, @end_time)
  end




  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end


  def included?(guess, grid)
    guess = guess.chars
    guess.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time])

    result
  end

  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def get_translation(word)
    api_key = "YOUR_SYSTRAN_API_KEY"
    begin
      response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
      json = JSON.parse(response.read.to_s)
      if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
        return json['outputs'][0]['output']
      end
    rescue
      if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
        return word
      else
        return nil
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/word_game_helper.rb
module WordGameHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/word_game/game.html.erb
<!-- <h1>WordGame#game</h1>
<p>Find me in app/views/word_game/game.html.erb</p>
 -->
<h1>******** Welcome to the longest word-game !********</h1>
<h2>Here is your grid :</h2>
<% #grid = generate_grid(9) %>
<%= @grid.join(" ") %>

<h2>What's your best shot ?</h2>

<% #@start_time = Time.now %>

<form action="/score" method="get">
  <input type="hidden" name=start_time value="<%= @start_time %>" >
  <input type="text" name="attempt" placeholder="Try your best!">
  <input type="hidden" name="grid" value="<%= @grid %>">
  <input type="submit">
</form>

<!-- attempt = gets.chomp -->

<% #@end_time = Time.now %>

app/views/word_game/home.html.erb
<h1>HELLO!</h1>

<%= link_to "Start the game!", game_path %>

app/views/word_game/score.html.erb
<!-- <h1>WordGame#score</h1>
<p>Find me in app/views/word_game/score.html.erb</p> -->

<% #result = run_game(attempt, grid, start_time, end_time) %>

<% #@end_time = Time.now %>

<p> Your word: <%= @attempt %> </p>
<p>Time Taken to answer: <%= @result[:time] %> </p>
<p>Translation: <%= @result[:translation] %> </p>
<p>Your score: <%= @result[:score] %> </p>
<p>Message: <%= @result[:message] %> </p>
<%= link_to "Return to Home!", root_path %>
<%= link_to "Play again!", game_path %>